# Generated by Django 3.0.7 on 2020-08-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_group', models.CharField(blank=True, max_length=3, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_account', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manifold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifold_id', models.IntegerField(blank=True, null=True)),
                ('part_number', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'manifolds',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manifoldconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manifold_id', models.IntegerField(blank=True, null=True)),
                ('station', models.IntegerField(blank=True, null=True)),
                ('fc_ports', models.CharField(blank=True, max_length=255, null=True)),
                ('fc_direct', models.CharField(blank=True, max_length=255, null=True)),
                ('cb_ports', models.CharField(blank=True, max_length=255, null=True)),
                ('red_ports', models.CharField(blank=True, max_length=255, null=True)),
                ('po_ports', models.CharField(blank=True, max_length=255, null=True)),
                ('rel_ports', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'manifoldconfig',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(blank=True, max_length=7, null=True)),
                ('created_on', models.DateTimeField()),
                ('project_notes1', models.TextField(blank=True)),
                ('project_notes2', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': True,
            },
        ),
    ]
