# Generated by Django 4.0.6 on 2022-08-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manifold', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('on_hand', models.IntegerField(blank=True, null=True)),
                ('stockstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('cost_each', models.FloatField(blank=True, null=True)),
                ('list_price', models.FloatField(blank=True, null=True)),
                ('leadtime', models.IntegerField(blank=True, null=True)),
                ('saleslinedisc', models.CharField(blank=True, max_length=255, null=True)),
                ('purchlinedisc', models.CharField(blank=True, max_length=255, null=True)),
                ('costpricedate', models.DateField(blank=True, null=True)),
                ('listpricedate', models.DateField(blank=True, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=255, null=True)),
                ('goto_item', models.CharField(blank=True, max_length=255, null=True)),
                ('gotomaxqty', models.CharField(blank=True, max_length=255, null=True)),
                ('csiaccount', models.CharField(blank=True, max_length=255, null=True)),
                ('csisalesrep', models.CharField(blank=True, max_length=255, null=True)),
                ('csicustname', models.CharField(blank=True, max_length=255, null=True)),
                ('csianniversarydate', models.DateField(blank=True, null=True)),
                ('csilastreviewdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parts',
                'managed': False,
            },
        ),
    ]
