# Generated by Django 3.0.7 on 2020-07-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_group', models.CharField(blank=True, max_length=3, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_account', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name_plural': 'customer',
                'db_table': 'customers',
                'managed': False,
            },
        ),
    ]
