# Generated by Django 3.0.7 on 2020-08-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BellHousingSizes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, max_length=255, null=True)),
                ('end_style', models.CharField(blank=True, max_length=255, null=True)),
                ('face_to_face', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('modifier', models.CharField(blank=True, max_length=255, null=True)),
                ('frame_size', models.CharField(blank=True, max_length=255, null=True)),
                ('max_coupling_size', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'bell_housing_sizes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CouplingCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('sizes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'coupling_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_number', models.CharField(blank=True, max_length=255)),
                ('frame_size', models.CharField(blank=True, max_length=255, null=True)),
                ('shaft_length', models.CharField(blank=True, max_length=255, null=True)),
                ('hp', models.FloatField(blank=True, null=True)),
                ('voltage', models.CharField(blank=True, max_length=255, null=True)),
                ('coupling_max', models.CharField(blank=True, max_length=255, null=True)),
                ('coupling_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'motors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(blank=True, max_length=7, null=True)),
                ('created_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pumpcodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump', models.CharField(blank=True, max_length=255, null=True)),
                ('pump_size', models.CharField(blank=True, max_length=255, null=True)),
                ('pump_suction', models.CharField(blank=True, max_length=255, null=True)),
                ('pump_suction_style', models.CharField(blank=True, max_length=255, null=True)),
                ('pump_pressure', models.CharField(blank=True, max_length=255, null=True)),
                ('pump_pressure_style', models.CharField(blank=True, max_length=255, null=True)),
                ('pump_case', models.CharField(blank=True, max_length=255, null=True)),
                ('pump_case_style', models.CharField(blank=True, max_length=255, null=True)),
                ('pump_flange', models.CharField(blank=True, max_length=255, null=True)),
                ('pump_shaft_length', models.CharField(blank=True, max_length=255, null=True)),
                ('pump_coupling_code', models.CharField(blank=True, max_length=255, null=True)),
                ('pump_shaft_style', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pumpcodes',
                'managed': True,
            },
        ),
    ]
