# Generated by Django 3.0.7 on 2020-08-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newunit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pumpcodes',
            name='pump_class',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pumpcodes',
            name='pump_shaft_length',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
