# Generated by Django 4.0.6 on 2022-08-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newunit', '0002_auto_20200807_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservoir_size', models.CharField(blank=True, max_length=255, null=True)),
                ('reservoir_configuration', models.CharField(blank=True, max_length=255, null=True)),
                ('part_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'reservoir',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Throughdrives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rear_pump', models.CharField(blank=True, max_length=255, null=True)),
                ('a4vso250', models.CharField(blank=True, max_length=255, null=True)),
                ('a4vso180', models.CharField(blank=True, max_length=255, null=True)),
                ('a4vso125', models.CharField(blank=True, max_length=255, null=True)),
                ('a4vso71', models.CharField(blank=True, max_length=255, null=True)),
                ('a4vso40', models.CharField(blank=True, max_length=255, null=True)),
                ('a10vso180_32', models.CharField(blank=True, max_length=255, null=True)),
                ('a10vso140_32', models.CharField(blank=True, max_length=255, null=True)),
                ('a10vso100_32', models.CharField(blank=True, max_length=255, null=True)),
                ('a10vso71_32', models.CharField(blank=True, max_length=255, null=True)),
                ('a10vso45_32', models.CharField(blank=True, max_length=255, null=True)),
                ('a15vso280', models.CharField(blank=True, max_length=255, null=True)),
                ('a15vso210', models.CharField(blank=True, max_length=255, null=True)),
                ('a15vso175', models.CharField(blank=True, max_length=255, null=True)),
                ('a15vso145', models.CharField(blank=True, max_length=255, null=True)),
                ('a15vso110', models.CharField(blank=True, max_length=255, null=True)),
                ('a10vso140_31', models.CharField(blank=True, max_length=255, null=True)),
                ('a10vso100_31', models.CharField(blank=True, max_length=255, null=True)),
                ('a10vso71_31', models.CharField(blank=True, max_length=255, null=True)),
                ('a10vso45_31', models.CharField(blank=True, max_length=255, null=True)),
                ('a10vso28_31', models.CharField(blank=True, max_length=255, null=True)),
                ('a10vso18_31', models.CharField(blank=True, max_length=255, null=True)),
                ('azpf', models.CharField(blank=True, max_length=255, null=True)),
                ('azpg', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('azpb', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'throughdrives',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='pumpcodes',
            name='front_pump',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pumpcodes',
            name='rear_pump',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
